// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/article.proto

package article

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ArticlesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticlesRequest) Reset()         { *m = ArticlesRequest{} }
func (m *ArticlesRequest) String() string { return proto.CompactTextString(m) }
func (*ArticlesRequest) ProtoMessage()    {}
func (*ArticlesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60692e730edf4587, []int{0}
}

func (m *ArticlesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticlesRequest.Unmarshal(m, b)
}
func (m *ArticlesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticlesRequest.Marshal(b, m, deterministic)
}
func (m *ArticlesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticlesRequest.Merge(m, src)
}
func (m *ArticlesRequest) XXX_Size() int {
	return xxx_messageInfo_ArticlesRequest.Size(m)
}
func (m *ArticlesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticlesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ArticlesRequest proto.InternalMessageInfo

type ArticlesResponse struct {
	Articles             []*ArticleResponse `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ArticlesResponse) Reset()         { *m = ArticlesResponse{} }
func (m *ArticlesResponse) String() string { return proto.CompactTextString(m) }
func (*ArticlesResponse) ProtoMessage()    {}
func (*ArticlesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60692e730edf4587, []int{1}
}

func (m *ArticlesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticlesResponse.Unmarshal(m, b)
}
func (m *ArticlesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticlesResponse.Marshal(b, m, deterministic)
}
func (m *ArticlesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticlesResponse.Merge(m, src)
}
func (m *ArticlesResponse) XXX_Size() int {
	return xxx_messageInfo_ArticlesResponse.Size(m)
}
func (m *ArticlesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticlesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ArticlesResponse proto.InternalMessageInfo

func (m *ArticlesResponse) GetArticles() []*ArticleResponse {
	if m != nil {
		return m.Articles
	}
	return nil
}

type ArticleRequest struct {
	ArticleId            string   `protobuf:"bytes,1,opt,name=articleId,proto3" json:"articleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleRequest) Reset()         { *m = ArticleRequest{} }
func (m *ArticleRequest) String() string { return proto.CompactTextString(m) }
func (*ArticleRequest) ProtoMessage()    {}
func (*ArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60692e730edf4587, []int{2}
}

func (m *ArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleRequest.Unmarshal(m, b)
}
func (m *ArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleRequest.Marshal(b, m, deterministic)
}
func (m *ArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleRequest.Merge(m, src)
}
func (m *ArticleRequest) XXX_Size() int {
	return xxx_messageInfo_ArticleRequest.Size(m)
}
func (m *ArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleRequest proto.InternalMessageInfo

func (m *ArticleRequest) GetArticleId() string {
	if m != nil {
		return m.ArticleId
	}
	return ""
}

type ArticleResponse struct {
	ArticleId            string               `protobuf:"bytes,1,opt,name=articleId,proto3" json:"articleId,omitempty"`
	ArticleName          string               `protobuf:"bytes,2,opt,name=articleName,proto3" json:"articleName,omitempty"`
	Editor               string               `protobuf:"bytes,3,opt,name=editor,proto3" json:"editor,omitempty"`
	LastModified         *timestamp.Timestamp `protobuf:"bytes,4,opt,name=lastModified,proto3" json:"lastModified,omitempty"`
	Thumbnail            string               `protobuf:"bytes,5,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Description          string               `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Content              *_struct.Struct      `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	EditorIcon           string               `protobuf:"bytes,8,opt,name=editorIcon,proto3" json:"editorIcon,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ArticleResponse) Reset()         { *m = ArticleResponse{} }
func (m *ArticleResponse) String() string { return proto.CompactTextString(m) }
func (*ArticleResponse) ProtoMessage()    {}
func (*ArticleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60692e730edf4587, []int{3}
}

func (m *ArticleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleResponse.Unmarshal(m, b)
}
func (m *ArticleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleResponse.Marshal(b, m, deterministic)
}
func (m *ArticleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleResponse.Merge(m, src)
}
func (m *ArticleResponse) XXX_Size() int {
	return xxx_messageInfo_ArticleResponse.Size(m)
}
func (m *ArticleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleResponse proto.InternalMessageInfo

func (m *ArticleResponse) GetArticleId() string {
	if m != nil {
		return m.ArticleId
	}
	return ""
}

func (m *ArticleResponse) GetArticleName() string {
	if m != nil {
		return m.ArticleName
	}
	return ""
}

func (m *ArticleResponse) GetEditor() string {
	if m != nil {
		return m.Editor
	}
	return ""
}

func (m *ArticleResponse) GetLastModified() *timestamp.Timestamp {
	if m != nil {
		return m.LastModified
	}
	return nil
}

func (m *ArticleResponse) GetThumbnail() string {
	if m != nil {
		return m.Thumbnail
	}
	return ""
}

func (m *ArticleResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ArticleResponse) GetContent() *_struct.Struct {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *ArticleResponse) GetEditorIcon() string {
	if m != nil {
		return m.EditorIcon
	}
	return ""
}

type StoreEditorRequest struct {
	Editor               *Editor  `protobuf:"bytes,1,opt,name=editor,proto3" json:"editor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreEditorRequest) Reset()         { *m = StoreEditorRequest{} }
func (m *StoreEditorRequest) String() string { return proto.CompactTextString(m) }
func (*StoreEditorRequest) ProtoMessage()    {}
func (*StoreEditorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60692e730edf4587, []int{4}
}

func (m *StoreEditorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreEditorRequest.Unmarshal(m, b)
}
func (m *StoreEditorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreEditorRequest.Marshal(b, m, deterministic)
}
func (m *StoreEditorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreEditorRequest.Merge(m, src)
}
func (m *StoreEditorRequest) XXX_Size() int {
	return xxx_messageInfo_StoreEditorRequest.Size(m)
}
func (m *StoreEditorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreEditorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreEditorRequest proto.InternalMessageInfo

func (m *StoreEditorRequest) GetEditor() *Editor {
	if m != nil {
		return m.Editor
	}
	return nil
}

type Editor struct {
	EditorId             int32    `protobuf:"varint,1,opt,name=editorId,proto3" json:"editorId,omitempty"`
	EditorName           string   `protobuf:"bytes,2,opt,name=editorName,proto3" json:"editorName,omitempty"`
	EditorIcon           string   `protobuf:"bytes,3,opt,name=editorIcon,proto3" json:"editorIcon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Editor) Reset()         { *m = Editor{} }
func (m *Editor) String() string { return proto.CompactTextString(m) }
func (*Editor) ProtoMessage()    {}
func (*Editor) Descriptor() ([]byte, []int) {
	return fileDescriptor_60692e730edf4587, []int{5}
}

func (m *Editor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Editor.Unmarshal(m, b)
}
func (m *Editor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Editor.Marshal(b, m, deterministic)
}
func (m *Editor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Editor.Merge(m, src)
}
func (m *Editor) XXX_Size() int {
	return xxx_messageInfo_Editor.Size(m)
}
func (m *Editor) XXX_DiscardUnknown() {
	xxx_messageInfo_Editor.DiscardUnknown(m)
}

var xxx_messageInfo_Editor proto.InternalMessageInfo

func (m *Editor) GetEditorId() int32 {
	if m != nil {
		return m.EditorId
	}
	return 0
}

func (m *Editor) GetEditorName() string {
	if m != nil {
		return m.EditorName
	}
	return ""
}

func (m *Editor) GetEditorIcon() string {
	if m != nil {
		return m.EditorIcon
	}
	return ""
}

type StoreEditorResponse struct {
	Editor               *Editor  `protobuf:"bytes,1,opt,name=editor,proto3" json:"editor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreEditorResponse) Reset()         { *m = StoreEditorResponse{} }
func (m *StoreEditorResponse) String() string { return proto.CompactTextString(m) }
func (*StoreEditorResponse) ProtoMessage()    {}
func (*StoreEditorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60692e730edf4587, []int{6}
}

func (m *StoreEditorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreEditorResponse.Unmarshal(m, b)
}
func (m *StoreEditorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreEditorResponse.Marshal(b, m, deterministic)
}
func (m *StoreEditorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreEditorResponse.Merge(m, src)
}
func (m *StoreEditorResponse) XXX_Size() int {
	return xxx_messageInfo_StoreEditorResponse.Size(m)
}
func (m *StoreEditorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreEditorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StoreEditorResponse proto.InternalMessageInfo

func (m *StoreEditorResponse) GetEditor() *Editor {
	if m != nil {
		return m.Editor
	}
	return nil
}

func init() {
	proto.RegisterType((*ArticlesRequest)(nil), "article.ArticlesRequest")
	proto.RegisterType((*ArticlesResponse)(nil), "article.ArticlesResponse")
	proto.RegisterType((*ArticleRequest)(nil), "article.ArticleRequest")
	proto.RegisterType((*ArticleResponse)(nil), "article.ArticleResponse")
	proto.RegisterType((*StoreEditorRequest)(nil), "article.StoreEditorRequest")
	proto.RegisterType((*Editor)(nil), "article.Editor")
	proto.RegisterType((*StoreEditorResponse)(nil), "article.StoreEditorResponse")
}

func init() {
	proto.RegisterFile("proto/article.proto", fileDescriptor_60692e730edf4587)
}

var fileDescriptor_60692e730edf4587 = []byte{
	// 509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0x13, 0x9a, 0xa4, 0xe3, 0xa8, 0x85, 0x29, 0xd0, 0xc5, 0x8d, 0xc0, 0xda, 0x0b, 0x39,
	0xd9, 0x6a, 0xe0, 0x84, 0x44, 0x25, 0x84, 0x40, 0xf4, 0x00, 0x07, 0x97, 0x0b, 0x47, 0xc7, 0xde,
	0x96, 0x95, 0x12, 0xaf, 0xeb, 0xdd, 0x70, 0x41, 0x5c, 0x78, 0x05, 0xde, 0x80, 0xe7, 0xe0, 0x2d,
	0x78, 0x05, 0x1e, 0x04, 0x65, 0xff, 0xe2, 0xd6, 0x0d, 0x42, 0x3d, 0xce, 0xf7, 0xcd, 0xce, 0xf7,
	0x69, 0xe6, 0x5b, 0x38, 0xa8, 0x1b, 0xa1, 0x44, 0x9a, 0x37, 0x8a, 0x17, 0x0b, 0x96, 0xe8, 0x0a,
	0x87, 0xb6, 0x8c, 0x9e, 0x5c, 0x08, 0x71, 0xb1, 0x60, 0xa9, 0x86, 0xe7, 0xab, 0xf3, 0x54, 0xf1,
	0x25, 0x93, 0x2a, 0x5f, 0xd6, 0xa6, 0x33, 0x9a, 0xd8, 0x86, 0xbc, 0xe6, 0x69, 0x5e, 0x55, 0x42,
	0xe5, 0x8a, 0x8b, 0x4a, 0x5e, 0x63, 0xfd, 0x73, 0xa9, 0x9a, 0x55, 0xa1, 0x0c, 0x4b, 0xef, 0xc1,
	0xfe, 0x2b, 0xa3, 0x23, 0x33, 0x76, 0xb9, 0x62, 0x52, 0xd1, 0x77, 0x70, 0x77, 0x03, 0xc9, 0x5a,
	0x54, 0x92, 0xe1, 0x73, 0x18, 0x59, 0x3b, 0x92, 0x04, 0x71, 0x7f, 0x1a, 0xce, 0x48, 0xe2, 0xec,
	0xda, 0x66, 0xd7, 0x9b, 0xf9, 0x4e, 0x9a, 0xc0, 0x9e, 0x27, 0xf5, 0x6c, 0x9c, 0xc0, 0xae, 0x65,
	0x4f, 0x4b, 0x12, 0xc4, 0xc1, 0x74, 0x37, 0xdb, 0x00, 0xf4, 0x57, 0xcf, 0xbb, 0xf1, 0xca, 0xff,
	0x7c, 0x81, 0x31, 0x84, 0xb6, 0xf8, 0x90, 0x2f, 0x19, 0xe9, 0x69, 0xbe, 0x0d, 0xe1, 0x43, 0x18,
	0xb0, 0x92, 0x2b, 0xd1, 0x90, 0xbe, 0x26, 0x6d, 0x85, 0x27, 0x30, 0x5e, 0xe4, 0x52, 0xbd, 0x17,
	0x25, 0x3f, 0xe7, 0xac, 0x24, 0x77, 0xe2, 0x60, 0x1a, 0xce, 0xa2, 0xc4, 0x6c, 0x2b, 0x71, 0xdb,
	0x4a, 0x3e, 0xba, 0x65, 0x67, 0x57, 0xfa, 0xd7, 0xbe, 0xd4, 0xe7, 0xd5, 0x72, 0x5e, 0xe5, 0x7c,
	0x41, 0x76, 0x8c, 0x2f, 0x0f, 0xac, 0x7d, 0x95, 0x4c, 0x16, 0x0d, 0xaf, 0xd7, 0xa7, 0x20, 0x03,
	0xe3, 0xab, 0x05, 0xe1, 0x31, 0x0c, 0x0b, 0x51, 0x29, 0x56, 0x29, 0x32, 0xd4, 0xd2, 0x87, 0x1d,
	0xe9, 0x33, 0x7d, 0xa8, 0xcc, 0xf5, 0xe1, 0x63, 0x00, 0x63, 0xfe, 0xb4, 0x10, 0x15, 0x19, 0xe9,
	0x99, 0x2d, 0x84, 0xbe, 0x04, 0x3c, 0x53, 0xa2, 0x61, 0x6f, 0x34, 0xe4, 0x56, 0xfe, 0xd4, 0x2f,
	0x20, 0xd0, 0x3a, 0xfb, 0xfe, 0x70, 0xb6, 0xcf, 0xd2, 0xb4, 0x84, 0x81, 0x41, 0x30, 0x82, 0x91,
	0x1d, 0x6b, 0x56, 0xbe, 0x93, 0xf9, 0x7a, 0x63, 0xa2, 0xb5, 0xf0, 0x16, 0x72, 0xcd, 0x64, 0xbf,
	0x63, 0xf2, 0x04, 0x0e, 0xae, 0x98, 0xb4, 0x67, 0xfe, 0x5f, 0x97, 0xb3, 0x9f, 0x7d, 0x18, 0xda,
	0x8c, 0xe0, 0x27, 0x18, 0xbf, 0xe5, 0x55, 0xe9, 0xd2, 0x8a, 0x9d, 0x4c, 0xba, 0x4c, 0x47, 0x8f,
	0x6e, 0x60, 0x8c, 0x32, 0xbd, 0xff, 0xfd, 0xf7, 0x9f, 0x1f, 0xbd, 0x3d, 0x1c, 0xa7, 0x5f, 0x8e,
	0xdd, 0x17, 0x94, 0x38, 0x87, 0xb0, 0x35, 0x1a, 0x0f, 0xbb, 0x69, 0x37, 0x83, 0xb7, 0x7e, 0x03,
	0x1a, 0xeb, 0xb9, 0x11, 0x92, 0xf6, 0xdc, 0xf4, 0xab, 0xcf, 0xee, 0x37, 0xbc, 0x04, 0x6c, 0x69,
	0xbc, 0xb6, 0x57, 0xbe, 0x85, 0xd4, 0x54, 0x4b, 0x51, 0x8c, 0xb7, 0x49, 0xa5, 0x2e, 0x42, 0x0c,
	0xc2, 0xd6, 0xf6, 0xf1, 0xc8, 0x8f, 0xec, 0x06, 0x27, 0x9a, 0xdc, 0x4c, 0x5a, 0xcd, 0x23, 0xad,
	0xf9, 0x80, 0x86, 0x6b, 0x4d, 0x73, 0x1b, 0xf9, 0xc2, 0x1e, 0x69, 0x3e, 0xd0, 0x19, 0x7e, 0xf6,
	0x37, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x0f, 0x35, 0x76, 0xd9, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ArticleClient is the client API for Article service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ArticleClient interface {
	FindArticles(ctx context.Context, in *ArticlesRequest, opts ...grpc.CallOption) (*ArticlesResponse, error)
	FindArticle(ctx context.Context, in *ArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error)
	FindArticleContent(ctx context.Context, in *ArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error)
	StoreEditor(ctx context.Context, in *StoreEditorRequest, opts ...grpc.CallOption) (*StoreEditorResponse, error)
}

type articleClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleClient(cc grpc.ClientConnInterface) ArticleClient {
	return &articleClient{cc}
}

func (c *articleClient) FindArticles(ctx context.Context, in *ArticlesRequest, opts ...grpc.CallOption) (*ArticlesResponse, error) {
	out := new(ArticlesResponse)
	err := c.cc.Invoke(ctx, "/article.Article/FindArticles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) FindArticle(ctx context.Context, in *ArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error) {
	out := new(ArticleResponse)
	err := c.cc.Invoke(ctx, "/article.Article/FindArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) FindArticleContent(ctx context.Context, in *ArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error) {
	out := new(ArticleResponse)
	err := c.cc.Invoke(ctx, "/article.Article/FindArticleContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) StoreEditor(ctx context.Context, in *StoreEditorRequest, opts ...grpc.CallOption) (*StoreEditorResponse, error) {
	out := new(StoreEditorResponse)
	err := c.cc.Invoke(ctx, "/article.Article/StoreEditor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServer is the server API for Article service.
type ArticleServer interface {
	FindArticles(context.Context, *ArticlesRequest) (*ArticlesResponse, error)
	FindArticle(context.Context, *ArticleRequest) (*ArticleResponse, error)
	FindArticleContent(context.Context, *ArticleRequest) (*ArticleResponse, error)
	StoreEditor(context.Context, *StoreEditorRequest) (*StoreEditorResponse, error)
}

// UnimplementedArticleServer can be embedded to have forward compatible implementations.
type UnimplementedArticleServer struct {
}

func (*UnimplementedArticleServer) FindArticles(ctx context.Context, req *ArticlesRequest) (*ArticlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindArticles not implemented")
}
func (*UnimplementedArticleServer) FindArticle(ctx context.Context, req *ArticleRequest) (*ArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindArticle not implemented")
}
func (*UnimplementedArticleServer) FindArticleContent(ctx context.Context, req *ArticleRequest) (*ArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindArticleContent not implemented")
}
func (*UnimplementedArticleServer) StoreEditor(ctx context.Context, req *StoreEditorRequest) (*StoreEditorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreEditor not implemented")
}

func RegisterArticleServer(s *grpc.Server, srv ArticleServer) {
	s.RegisterService(&_Article_serviceDesc, srv)
}

func _Article_FindArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).FindArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.Article/FindArticles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).FindArticles(ctx, req.(*ArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_FindArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).FindArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.Article/FindArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).FindArticle(ctx, req.(*ArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_FindArticleContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).FindArticleContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.Article/FindArticleContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).FindArticleContent(ctx, req.(*ArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_StoreEditor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreEditorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).StoreEditor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.Article/StoreEditor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).StoreEditor(ctx, req.(*StoreEditorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Article_serviceDesc = grpc.ServiceDesc{
	ServiceName: "article.Article",
	HandlerType: (*ArticleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindArticles",
			Handler:    _Article_FindArticles_Handler,
		},
		{
			MethodName: "FindArticle",
			Handler:    _Article_FindArticle_Handler,
		},
		{
			MethodName: "FindArticleContent",
			Handler:    _Article_FindArticleContent_Handler,
		},
		{
			MethodName: "StoreEditor",
			Handler:    _Article_StoreEditor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/article.proto",
}
