// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/article.proto

package article

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ArticlesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticlesRequest) Reset()         { *m = ArticlesRequest{} }
func (m *ArticlesRequest) String() string { return proto.CompactTextString(m) }
func (*ArticlesRequest) ProtoMessage()    {}
func (*ArticlesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60692e730edf4587, []int{0}
}

func (m *ArticlesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticlesRequest.Unmarshal(m, b)
}
func (m *ArticlesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticlesRequest.Marshal(b, m, deterministic)
}
func (m *ArticlesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticlesRequest.Merge(m, src)
}
func (m *ArticlesRequest) XXX_Size() int {
	return xxx_messageInfo_ArticlesRequest.Size(m)
}
func (m *ArticlesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticlesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ArticlesRequest proto.InternalMessageInfo

type ArticlesResponse struct {
	Articles             []*ArticleResponse `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ArticlesResponse) Reset()         { *m = ArticlesResponse{} }
func (m *ArticlesResponse) String() string { return proto.CompactTextString(m) }
func (*ArticlesResponse) ProtoMessage()    {}
func (*ArticlesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60692e730edf4587, []int{1}
}

func (m *ArticlesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticlesResponse.Unmarshal(m, b)
}
func (m *ArticlesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticlesResponse.Marshal(b, m, deterministic)
}
func (m *ArticlesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticlesResponse.Merge(m, src)
}
func (m *ArticlesResponse) XXX_Size() int {
	return xxx_messageInfo_ArticlesResponse.Size(m)
}
func (m *ArticlesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticlesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ArticlesResponse proto.InternalMessageInfo

func (m *ArticlesResponse) GetArticles() []*ArticleResponse {
	if m != nil {
		return m.Articles
	}
	return nil
}

type ArticleRequest struct {
	ArticleId            string   `protobuf:"bytes,1,opt,name=articleId,proto3" json:"articleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleRequest) Reset()         { *m = ArticleRequest{} }
func (m *ArticleRequest) String() string { return proto.CompactTextString(m) }
func (*ArticleRequest) ProtoMessage()    {}
func (*ArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60692e730edf4587, []int{2}
}

func (m *ArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleRequest.Unmarshal(m, b)
}
func (m *ArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleRequest.Marshal(b, m, deterministic)
}
func (m *ArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleRequest.Merge(m, src)
}
func (m *ArticleRequest) XXX_Size() int {
	return xxx_messageInfo_ArticleRequest.Size(m)
}
func (m *ArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleRequest proto.InternalMessageInfo

func (m *ArticleRequest) GetArticleId() string {
	if m != nil {
		return m.ArticleId
	}
	return ""
}

type ArticleResponse struct {
	ArticleId            string               `protobuf:"bytes,1,opt,name=articleId,proto3" json:"articleId,omitempty"`
	ArticleName          string               `protobuf:"bytes,2,opt,name=articleName,proto3" json:"articleName,omitempty"`
	Editor               string               `protobuf:"bytes,3,opt,name=editor,proto3" json:"editor,omitempty"`
	LastModified         *timestamp.Timestamp `protobuf:"bytes,4,opt,name=lastModified,proto3" json:"lastModified,omitempty"`
	Thumbnail            string               `protobuf:"bytes,5,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Description          string               `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Content              string               `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ArticleResponse) Reset()         { *m = ArticleResponse{} }
func (m *ArticleResponse) String() string { return proto.CompactTextString(m) }
func (*ArticleResponse) ProtoMessage()    {}
func (*ArticleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60692e730edf4587, []int{3}
}

func (m *ArticleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleResponse.Unmarshal(m, b)
}
func (m *ArticleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleResponse.Marshal(b, m, deterministic)
}
func (m *ArticleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleResponse.Merge(m, src)
}
func (m *ArticleResponse) XXX_Size() int {
	return xxx_messageInfo_ArticleResponse.Size(m)
}
func (m *ArticleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleResponse proto.InternalMessageInfo

func (m *ArticleResponse) GetArticleId() string {
	if m != nil {
		return m.ArticleId
	}
	return ""
}

func (m *ArticleResponse) GetArticleName() string {
	if m != nil {
		return m.ArticleName
	}
	return ""
}

func (m *ArticleResponse) GetEditor() string {
	if m != nil {
		return m.Editor
	}
	return ""
}

func (m *ArticleResponse) GetLastModified() *timestamp.Timestamp {
	if m != nil {
		return m.LastModified
	}
	return nil
}

func (m *ArticleResponse) GetThumbnail() string {
	if m != nil {
		return m.Thumbnail
	}
	return ""
}

func (m *ArticleResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ArticleResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*ArticlesRequest)(nil), "article.ArticlesRequest")
	proto.RegisterType((*ArticlesResponse)(nil), "article.ArticlesResponse")
	proto.RegisterType((*ArticleRequest)(nil), "article.ArticleRequest")
	proto.RegisterType((*ArticleResponse)(nil), "article.ArticleResponse")
}

func init() {
	proto.RegisterFile("proto/article.proto", fileDescriptor_60692e730edf4587)
}

var fileDescriptor_60692e730edf4587 = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xcd, 0x6e, 0xd3, 0x40,
	0x18, 0x94, 0x1d, 0x88, 0xc9, 0x3a, 0x0a, 0xf0, 0x81, 0x60, 0xb1, 0x22, 0x61, 0xf9, 0xe4, 0x93,
	0x2d, 0x02, 0x67, 0x24, 0x84, 0x84, 0xe0, 0x00, 0x07, 0x8b, 0x4b, 0x8f, 0xeb, 0x78, 0x93, 0xae,
	0x64, 0xef, 0x3a, 0xde, 0x4d, 0x2f, 0x55, 0x2f, 0xed, 0x23, 0xf4, 0x71, 0xfa, 0x18, 0x7d, 0x85,
	0x3e, 0x48, 0x95, 0xfd, 0x71, 0x5c, 0xa5, 0xe9, 0xa1, 0xc7, 0xef, 0x9b, 0xcf, 0x33, 0xe3, 0x99,
	0x45, 0xef, 0xda, 0x4e, 0x28, 0x91, 0x93, 0x4e, 0xb1, 0x65, 0x4d, 0x33, 0x3d, 0x41, 0x60, 0xc7,
	0xe8, 0xf3, 0x5a, 0x88, 0x75, 0x4d, 0x73, 0xbd, 0x2e, 0xb7, 0xab, 0x5c, 0xb1, 0x86, 0x4a, 0x45,
	0x9a, 0xd6, 0x5c, 0x46, 0x73, 0x7b, 0x40, 0x5a, 0x96, 0x13, 0xce, 0x85, 0x22, 0x8a, 0x09, 0x2e,
	0x0d, 0x9a, 0xbc, 0x45, 0xaf, 0x7f, 0x18, 0x26, 0x59, 0xd0, 0xcd, 0x96, 0x4a, 0x95, 0xfc, 0x46,
	0x6f, 0xf6, 0x2b, 0xd9, 0x0a, 0x2e, 0x29, 0x7c, 0x43, 0xaf, 0xac, 0xa0, 0xc4, 0x5e, 0x3c, 0x4a,
	0xc3, 0x05, 0xce, 0x9c, 0x21, 0x7b, 0xec, 0x6e, 0x8b, 0xfe, 0x32, 0xc9, 0xd0, 0xac, 0x07, 0x35,
	0x37, 0xcc, 0xd1, 0xc4, 0xa2, 0x7f, 0x2a, 0xec, 0xc5, 0x5e, 0x3a, 0x29, 0xf6, 0x8b, 0xe4, 0xca,
	0xef, 0xdd, 0xf4, 0xca, 0x4f, 0x7e, 0x01, 0x31, 0x0a, 0xed, 0xf0, 0x8f, 0x34, 0x14, 0xfb, 0x1a,
	0x1f, 0xae, 0xe0, 0x03, 0x1a, 0xd3, 0x8a, 0x29, 0xd1, 0xe1, 0x91, 0x06, 0xed, 0x04, 0xdf, 0xd1,
	0xb4, 0x26, 0x52, 0xfd, 0x15, 0x15, 0x5b, 0x31, 0x5a, 0xe1, 0x17, 0xb1, 0x97, 0x86, 0x8b, 0x28,
	0x33, 0x69, 0x65, 0x2e, 0xce, 0xec, 0xbf, 0x8b, 0xb3, 0x78, 0x70, 0xbf, 0xf3, 0xa5, 0x4e, 0xb7,
	0x4d, 0xc9, 0x09, 0xab, 0xf1, 0x4b, 0xe3, 0xab, 0x5f, 0xec, 0x7c, 0x55, 0x54, 0x2e, 0x3b, 0xd6,
	0xee, 0xc2, 0xc6, 0x63, 0xe3, 0x6b, 0xb0, 0x02, 0x8c, 0x82, 0xa5, 0xe0, 0x8a, 0x72, 0x85, 0x03,
	0x8d, 0xba, 0x71, 0x71, 0xe3, 0xa3, 0xc0, 0xa6, 0x00, 0x27, 0x68, 0xfa, 0x8b, 0xf1, 0xca, 0xf5,
	0x01, 0x07, 0xa9, 0xbb, 0xd6, 0xa2, 0x4f, 0x8f, 0x20, 0x26, 0xc2, 0xe4, 0xfd, 0xe5, 0xed, 0xdd,
	0xb5, 0x3f, 0x83, 0x69, 0x7e, 0xf6, 0xc5, 0x3d, 0x23, 0x09, 0x25, 0x0a, 0x07, 0xd4, 0xf0, 0xf1,
	0xb0, 0x4f, 0x43, 0x7c, 0xb4, 0xe8, 0x24, 0xd6, 0xbc, 0x11, 0xe0, 0x21, 0x6f, 0x7e, 0xde, 0xb7,
	0x73, 0x01, 0x1b, 0x04, 0x03, 0x8d, 0x9f, 0xe6, 0x07, 0x9f, 0x23, 0x95, 0x6a, 0xa9, 0x04, 0xe2,
	0x63, 0x52, 0xb9, 0x4d, 0xaf, 0x1c, 0xeb, 0xe6, 0xbe, 0xde, 0x07, 0x00, 0x00, 0xff, 0xff, 0x94,
	0x96, 0x8f, 0xac, 0x36, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ArticleClient is the client API for Article service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ArticleClient interface {
	FindArticles(ctx context.Context, in *ArticlesRequest, opts ...grpc.CallOption) (*ArticlesResponse, error)
	FindArticle(ctx context.Context, in *ArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error)
	FindArticleContent(ctx context.Context, in *ArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error)
}

type articleClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleClient(cc grpc.ClientConnInterface) ArticleClient {
	return &articleClient{cc}
}

func (c *articleClient) FindArticles(ctx context.Context, in *ArticlesRequest, opts ...grpc.CallOption) (*ArticlesResponse, error) {
	out := new(ArticlesResponse)
	err := c.cc.Invoke(ctx, "/article.Article/FindArticles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) FindArticle(ctx context.Context, in *ArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error) {
	out := new(ArticleResponse)
	err := c.cc.Invoke(ctx, "/article.Article/FindArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) FindArticleContent(ctx context.Context, in *ArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error) {
	out := new(ArticleResponse)
	err := c.cc.Invoke(ctx, "/article.Article/FindArticleContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServer is the server API for Article service.
type ArticleServer interface {
	FindArticles(context.Context, *ArticlesRequest) (*ArticlesResponse, error)
	FindArticle(context.Context, *ArticleRequest) (*ArticleResponse, error)
	FindArticleContent(context.Context, *ArticleRequest) (*ArticleResponse, error)
}

// UnimplementedArticleServer can be embedded to have forward compatible implementations.
type UnimplementedArticleServer struct {
}

func (*UnimplementedArticleServer) FindArticles(ctx context.Context, req *ArticlesRequest) (*ArticlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindArticles not implemented")
}
func (*UnimplementedArticleServer) FindArticle(ctx context.Context, req *ArticleRequest) (*ArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindArticle not implemented")
}
func (*UnimplementedArticleServer) FindArticleContent(ctx context.Context, req *ArticleRequest) (*ArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindArticleContent not implemented")
}

func RegisterArticleServer(s *grpc.Server, srv ArticleServer) {
	s.RegisterService(&_Article_serviceDesc, srv)
}

func _Article_FindArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).FindArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.Article/FindArticles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).FindArticles(ctx, req.(*ArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_FindArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).FindArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.Article/FindArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).FindArticle(ctx, req.(*ArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_FindArticleContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).FindArticleContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.Article/FindArticleContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).FindArticleContent(ctx, req.(*ArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Article_serviceDesc = grpc.ServiceDesc{
	ServiceName: "article.Article",
	HandlerType: (*ArticleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindArticles",
			Handler:    _Article_FindArticles_Handler,
		},
		{
			MethodName: "FindArticle",
			Handler:    _Article_FindArticle_Handler,
		},
		{
			MethodName: "FindArticleContent",
			Handler:    _Article_FindArticleContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/article.proto",
}
