apiVersion: apps/v1
kind: Deployment
metadata:
  name: research-api
  namespace: research
  labels:
    app: research-api
spec:
  selector:
    matchLabels:
      app: research-api
  replicas: 1
  template:
    metadata:
      labels:
        app: research-api
    spec:
      containers:
      - name: research-api
        image: "gcr.io/anan-project/research-api:${IMAGE_TAG}"
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 100Mi
        imagePullPolicy: Always
        ports:
        - containerPort: 19003
