name: research_front
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  angular_forms: ^2.1.2
  angular_router: ^2.0.0-alpha+22
  optional: ^4.0.1
  tuple: ^1.0.3
  equatable: ^1.0.3
  stream_transform: ^1.1.0

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: '>=1.8.0 <1.9.0'
  build_runner_core: '4.5.2'
  build_modules: '2.8.1'
  json_serializable: ^3.2.2
  build_test: ^0.10.8
  build_web_compilers: '>=2.9.0 <2.10.0'
  pedantic: ^1.8.0
  built_html: ^0.1.0
  sass_builder: ^2.1.3
  test: ^1.6.0
