apiVersion: v1
data:
  front.conf: |
    server {
      listen       80;
      server_name  localhost;

      proxy_connect_timeout 20;
      proxy_read_timeout    40;
      proxy_send_timeout    80;

      charset utf-8;

      gzip on;
      gzip_types text/css application/javascript application/json application/font-woff application/font-tff image/gif image/png image/jpeg application/octet-stream;

      location / {
        root   /usr/share/nginx/html;
        try_files $uri @index;
      }

      location @index {
        root   /usr/share/nginx/html;
        add_header Cache-Control no-cache;
        etag off;
        try_files /index.html =404;
      }
    }

kind: ConfigMap
metadata:
  name: research-front-nginx-config-${LABEL}
