steps:
    # This step builds the container image.
    - name: 'gcr.io/cloud-builders/docker'
      id: Build
      dir: 'environements/apps/research-db'
      entrypoint: 'ls'
      args:
      - '/workspace/environements/apps/research-db'

    # This step pushes the image to Container Registry
    # The PROJECT_ID and SHORT_SHA variables are automatically
    # replaced by Cloud Build.
    - name: 'gcr.io/cloud-builders/docker'
      id: Push
      args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/research-db:$SHORT_SHA'