steps:
    # This step builds the container image.
    - name: 'gcr.io/cloud-builders/docker'
      id: Build
      dir: 'environments/apps/research-db'
      entrypoint: './build.sh'
      args:
      - '$SHORT_SHA'

    # This step pushes the image to Container Registry
    # The PROJECT_ID and SHORT_SHA variables are automatically
    # replaced by Cloud Build.
    - name: 'gcr.io/cloud-builders/docker'
      id: Push
      args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/research-db:$SHORT_SHA'

    - name: 'gcr.io/cloud-builders/kubectl'
      id: Deploy
      dir: 'environments/apps/research-db'
      args:
      - 'apply'
      - '-f'
      - 'kubernetes.yml'
      env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=gke01'