apiVersion: v1
kind: Service
metadata:
  name: research-db-svc
  namespace: research
spec:
  type: ClusterIP
  selector:
    app: research-db
  ports:
  - name: http
    protocol: TCP
    port: 5432
    targetPort: 5432
