apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-gateway
  namespace: research
  labels:
    app: grpc-gateway
spec:
  selector:
    matchLabels:
      app: grpc-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc-gateway
    spec:
      containers:
      - name: grpc-gateway
        image: "gcr.io/anan-project/grpc-gateway:${IMAGE_TAG}"
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 100Mi
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
