apiVersion: v1
kind: Service
metadata:
  name: grpc-gateway-svc
  namespace: research
spec:
  type: ClusterIP
  selector:
    app: grpc-gateway
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
