apiVersion: v1
kind: Service
metadata:
  name: research-api-svc
  namespace: research
spec:
  type: ClusterIP
  selector:
    app: research-api
  ports:
  - name: http
    protocol: TCP
    port: 19003
    targetPort: 19003
